[colors]
[colors.primary]
background = "#0f1011"
foreground = "#dfe1e5"

[colors.normal]
black   = "#2b2d30"
red     = "#e57a3f"
green   = "#56b09a"
yellow  = "#f9e2af"
blue    = "#7d9cc9"
magenta = "#cba6f7"
cyan    = "#94e2d5"
white   = "#b8bcc2"

[colors.bright]
black   = "#43454a"
red     = "#e57a3f"
green   = "#56b09a"
yellow  = "#f9e2af"
blue    = "#7d9cc9"
magenta = "#cba6f7"
cyan    = "#94e2d5"
white   = "#dfe1e5"

[colors.cursor]
text   = "#0f1011"
cursor = "#dfe1e5"
