accent = "#89b4fa"
cursor = "#cdd6f4"
foreground = "#cdd6f4"
background = "#1e1e2e"
selection_foreground = "#e8f1ff"
selection_background = "#292b3b"

color0 = "#45475a"
color1 = "#e57a3f"
color2 = "#56b09a"
color3 = "#f9e2af"
color4 = "#89b4fa"
color5 = "#cba6f7"
color6 = "#94e2d5"
color7 = "#bac2de"
color8 = "#585b70"
color9 = "#e57a3f"
color10 = "#56b09a"
color11 = "#f9e2af"
color12 = "#89b4fa"
color13 = "#cba6f7"
color14 = "#94e2d5"
color15 = "#cdd6f4"
