accent = "#7d9cc9"
cursor = "#dfe1e5"
foreground = "#dfe1e5"
background = "#0f1011"
selection_foreground = "#e8f1ff"
selection_background = "#1e1f22"

color0 = "#2b2d30"
color1 = "#e57a3f"
color2 = "#56b09a"
color3 = "#f9e2af"
color4 = "#7d9cc9"
color5 = "#cba6f7"
color6 = "#94e2d5"
color7 = "#b8bcc2"
color8 = "#43454a"
color9 = "#e57a3f"
color10 = "#56b09a"
color11 = "#f9e2af"
color12 = "#7d9cc9"
color13 = "#cba6f7"
color14 = "#94e2d5"
color15 = "#dfe1e5"
