# Background and foreground colors
background = #0f1011
foreground = #dfe1e5

# Standard colors
palette = 0=#2b2d30
palette = 1=#e57a3f
palette = 2=#56b09a
palette = 3=#f9e2af
palette = 4=#7d9cc9
palette = 5=#cba6f7
palette = 6=#94e2d5
palette = 7=#b8bcc2

# Bright colors
palette = 8=#43454a
palette = 9=#e57a3f
palette = 10=#56b09a
palette = 11=#f9e2af
palette = 12=#7d9cc9
palette = 13=#cba6f7
palette = 14=#94e2d5
palette = 15=#dfe1e5
