-- Generated by hypr2lua-web.

hl.config({
  general = {
    col = {
      active_border = "rgb(303463)",
      inactive_border = "rgb(1a1b26)",
    },
    border_size = 2,
    gaps_in = 2,
    gaps_out = 4,
  },
  animations = {
    enabled = true,
  },
  decoration = {
    rounding = 14,
    shadow = {
      enabled = false,
      range = 15,
      render_power = 5,
      offset = "0 0",
    },
    blur = {
      enabled = true,
      size = 1,
      passes = 4,
      contrast = 1.1,
      brightness = 1.1,
      vibrancy = 0.2,
      vibrancy_darkness = 0.2,
      noise = 0.03,
      ignore_opacity = true,
      new_optimizations = true,
    },
    active_opacity = 0.93,
    inactive_opacity = 0.92,
    fullscreen_opacity = 1.0,
  },
})

hl.curve("calm", { type = "bezier", points = { { 0.25, 0.9 }, { 0.35, 1 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 4,
  bezier = "calm",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 4,
  bezier = "calm",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 3,
  bezier = "calm",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 4,
  bezier = "calm",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 3,
  bezier = "calm",
})
hl.animation({
  leaf = "fadeIn",
  enabled = true,
  speed = 3,
  bezier = "calm",
})
hl.animation({
  leaf = "fadeOut",
  enabled = true,
  speed = 2,
  bezier = "calm",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 3,
  bezier = "calm",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 3,
  bezier = "calm",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 2,
  bezier = "calm",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 4,
  bezier = "calm",
})

hl.layer_rule({
  blur = true,
  match = {
    namespace = "walker",
  },
})
hl.layer_rule({
  ignore_alpha = 0,
  match = {
    namespace = "walker",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "waybar",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "notifications",
  },
})
hl.layer_rule({
  ignore_alpha = 0,
  match = {
    namespace = "notifications",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "vicinae",
  },
})
hl.layer_rule({
  blur = true,
  match = {
    namespace = "swayosd",
  },
})
hl.layer_rule({
  ignore_alpha = 0.5,
  match = {
    namespace = "swayosd",
  },
})
hl.layer_rule({
  ignore_alpha = 0.1,
  match = {
    namespace = "waybar",
  },
})
hl.layer_rule({
  ignore_alpha = 0.1,
  match = {
    namespace = "vicinae",
  },
})
